#!/bin/env bash

# Description : show git commit graph using FZF

function isInstalled() {
	if [[ -z "$1" ]]; then
		return 1
	fi

	if ! which "$1" &>/dev/null; then
		echo "gitgraph error : $1 is not installed"
		return 1
	fi
	return 0
}

isInstalled "git" || exit 1
isInstalled "fzf" || exit 1

# must be inside a git repo
if ! git -C $(pwd) rev-parse --is-inside-work-tree &> /dev/null; then
	echo "gitgraph error : you are not in a git repo"
	exit 1
fi

hash=$(git log \
	--color=always \
	--reverse \
	--oneline \
	--graph \
	--all \
	--format="%C(auto)%h %C(green)%cr %C(reset)%s" \
	--reverse |\
fzf --no-multi \
	--ansi)

git show --color=always $(echo $hash | grep -o '[a-f0-9]\{7\}')
