#!/bin/env bash

if ! which fzf &>/dev/null; then
	echo "viz error : fzf is not installed"
	exit 1
fi

dirs=(
	"$HOME/scripts" 
	"$HOME/.config"
	"$HOME/github"
)

list=$(find "${dirs[@]}" -maxdepth 4 -type f -not -path '*/.git*')
select=$(printf "%s\n" "$list" | fzf --reverse --height 40%)

if [[ ! -f "$select" ]]; then
	echo "viz error : Non existant file"
	exit 1
fi

if [[ -n "$EDITOR" ]]; then
	$EDITOR "$select"
else
	vim "$select"
fi
