#!/bin/env bash

# Description : this utility connects to a wireguard tunnel via a FZF menu
if [[ $EUID -ne 0 ]]; then
	echo "wireg error : the script must be run as root"
	exit 0
fi

if which fzf &>/dev/null; then
	echo "wireg error : fzf is not installed"
	exit 1
fi

if which wireguard &>/dev/null; then
	echo "wireg error : wireguard is not installed"
	exit 1
fi

path="/etc/wireguard"
confs=$(ls "$path")

select=$(printf "%s\n" "$confs" |\
		sed 's/.conf//' |\
		fzf --no-multi \
			--reverse \
			--height 35%)

if [[ -z "$select" ]]; then
	echo "wgz error : No selection"
	exit 0
fi
# start the connection
wg-quick up $select

